/* Generated By:JJTree&JavaCC: Do not edit this line. JavammConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavammConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPORT = 7;
  /** RegularExpression Id. */
  int PUBLIC = 8;
  /** RegularExpression Id. */
  int RETURN = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int EXTENDS = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int STATIC = 15;
  /** RegularExpression Id. */
  int MAIN = 16;
  /** RegularExpression Id. */
  int LEFTBRACKET = 17;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 18;
  /** RegularExpression Id. */
  int SQUARERIGHTBRACKET = 19;
  /** RegularExpression Id. */
  int SQUARELEFTBRACKET = 20;
  /** RegularExpression Id. */
  int LEFTPARENTHESES = 21;
  /** RegularExpression Id. */
  int RIGHTPARENTHESES = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int SEMICOLON = 25;
  /** RegularExpression Id. */
  int EQUAL = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int LESS = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int MULT = 31;
  /** RegularExpression Id. */
  int DIV = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int NEG = 35;
  /** RegularExpression Id. */
  int THIS = 36;
  /** RegularExpression Id. */
  int NEW = 37;
  /** RegularExpression Id. */
  int LENGTH = 38;
  /** RegularExpression Id. */
  int BOOLEAN = 39;
  /** RegularExpression Id. */
  int INT = 40;
  /** RegularExpression Id. */
  int STRING = 41;
  /** RegularExpression Id. */
  int VOID = 42;
  /** RegularExpression Id. */
  int IDENTIFIER = 43;
  /** RegularExpression Id. */
  int INTEGERLITERAL = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"import\"",
    "\"public\"",
    "\"return\"",
    "\"class\"",
    "\"extends\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"static\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"]\"",
    "\"[\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"=\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "\"this\"",
    "\"new\"",
    "\"length\"",
    "\"boolean\"",
    "\"int\"",
    "\"String\"",
    "\"void\"",
    "<IDENTIFIER>",
    "<INTEGERLITERAL>",
  };

}
