/* Generated By:JavaCC: Do not edit this line. JavammTreeConstants.java Version 6.0_1 */
public interface JavammTreeConstants
{
  public int JJTJAVAMM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTVOID = 3;
  public int JJTDOT = 4;
  public int JJTLEFTPARENTHESES = 5;
  public int JJTRIGHTPARENTHESES = 6;
  public int JJTSEMICOLON = 7;
  public int JJTCOMMA = 8;
  public int JJTTYPEIMPORT = 9;
  public int JJTTYPE = 10;
  public int JJTMETHODDECLARATION = 11;
  public int JJTMODIFIER = 12;
  public int JJTLEFTBRACKET = 13;
  public int JJTRIGHTBRACKET = 14;
  public int JJTMAINDECLARATION = 15;
  public int JJTSTATIC = 16;
  public int JJTMAIN = 17;
  public int JJTSQUARELEFTBRACKET = 18;
  public int JJTSQUARERIGHTBRACKET = 19;
  public int JJTMETHODARGUMENTS = 20;
  public int JJTVARIABLEDECLARATION = 21;
  public int JJTVARIABLENAME = 22;
  public int JJTEQUAL = 23;
  public int JJTRETURN = 24;
  public int JJTCLASSDECLARATION = 25;
  public int JJTCLASSNAME = 26;
  public int JJTEXTENDS = 27;
  public int JJTLINESTATEMENT = 28;
  public int JJTLITERALLINESTATEMENT = 29;
  public int JJTIFSTATEMENT = 30;
  public int JJTIF = 31;
  public int JJTELSE = 32;
  public int JJTWHILESTATEMENT = 33;
  public int JJTWHILE = 34;
  public int JJTEXPRESSION = 35;
  public int JJTAND = 36;
  public int JJTLESS = 37;
  public int JJTPLUS = 38;
  public int JJTMINUS = 39;
  public int JJTMULT = 40;
  public int JJTDIV = 41;
  public int JJTINTEGER = 42;
  public int JJTBOOLEAN = 43;
  public int JJTTHIS = 44;
  public int JJTNEW = 45;
  public int JJTNEGATION = 46;
  public int JJTLENGTH = 47;
  public int JJTNEWEXPR = 48;


  public String[] jjtNodeName = {
    "JavaMM",
    "ImportDeclaration",
    "Identifier",
    "void",
    "Dot",
    "LeftParentheses",
    "RightParentheses",
    "Semicolon",
    "Comma",
    "TypeImport",
    "Type",
    "MethodDeclaration",
    "Modifier",
    "LeftBracket",
    "RightBracket",
    "MainDeclaration",
    "Static",
    "Main",
    "SquareLeftBracket",
    "SquareRightBracket",
    "MethodArguments",
    "VariableDeclaration",
    "VariableName",
    "Equal",
    "Return",
    "ClassDeclaration",
    "ClassName",
    "Extends",
    "LineStatement",
    "LiteralLineStatement",
    "IfStatement",
    "If",
    "Else",
    "WhileStatement",
    "While",
    "Expression",
    "And",
    "Less",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "Integer",
    "Boolean",
    "This",
    "New",
    "Negation",
    "Length",
    "NewExpr",
  };
}
/* JavaCC - OriginalChecksum=47cb6ea6326b7c1fec1a8841f6811673 (do not edit this line) */
