/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import symbols.SymbolsTable;
import symbols.*;

public class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected Javamm parser;
  protected String val;
  protected Descriptor descriptor;

  // Line where the node starts
  private int line;
  
  // Column where the node starts
  private int column;

  public Descriptor getDescriptor() {
    return descriptor;
  }

  public void setDescriptor(Descriptor descriptor) {
    this.descriptor = descriptor;
  }


  public SimpleNode(int i) {
    id = i;
    this.line = -1;
    this.column = -1;
  }

  public SimpleNode(Javamm p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public int getId() {
    return id;
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  public String jjtGetVal() {
    return val;
  }

  public void jjtSetVal(String val) {
    this.val = val;
  }

  public void jjtSetLine(int line){
    this.line = line;
  }

  public int jjtGetLine(){
    return this.line;
  }

  public void jjtSetColumn(int column){
    this.column = column;
  }

  public int jjtGetColumn(){
    return this.column;
  }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { return JavammTreeConstants.jjtNodeName[id]; }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

     public void dump(String prefix) {
      System.out.print(toString(prefix));
  
      if (children == null) {
        if (this.val != null) {
          System.out.print(" [" + this.val + "]");
        }
      }
      System.out.print('\n');
  
      if (children != null) {
        for (int i = 0; i < children.length; ++i) {
          SimpleNode n = (SimpleNode) children[i];
          if (n != null) {
            n.dump(prefix + "   ");
          }
        }
      }
    }

  public void createSymbolTable(SymbolsTable table) {
    if (children == null) return;

    for (int i = 0; i < children.length; i++) {
      ((SimpleNode) children[i]).createSymbolTable(table);
    }
  }

  public void dumpTest(String prefix,int depth) {
    if(depth < 0){
      return;
    }
    System.out.print(toString(prefix));

    if (children == null) {
      if (this.val != null) {
        System.out.print(" [" + this.val + "]");
      }
    }
    System.out.print('\n');

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode) children[i];
        if (n != null) {
          n.dumpTest(prefix + "   ",depth-1);
        }
      }
    }
  }

}

/* JavaCC - OriginalChecksum=82060f00f415ccddd8b9afbe32dd1481 (do not edit this line) */
