/* Generated By:JavaCC: Do not edit this line. JavammTreeConstants.java Version 6.1_2 */
/*public interface JavammTreeConstants
{
  public int JJTJAVAMM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTSTATIC = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTVOID = 4;
  public int JJTDOT = 5;
  public int JJTRETURNIMPORT = 6;
  public int JJTIMPORTARGS = 7;
  public int JJTTYPE = 8;
  public int JJTMETHODDECLARATION = 9;
  public int JJTMETHODHEADER = 10;
  public int JJTMODIFIER = 11;
  public int JJTMAINARGS = 12;
  public int JJTMAINDECLARATION = 13;
  public int JJTMETHODARGUMENTS = 14;
  public int JJTVARIABLEDECLARATION = 15;
  public int JJTCLASSTYPE = 16;
  public int JJTVARIABLENAME = 17;
  public int JJTEQUAL = 18;
  public int JJTRETURN = 19;
  public int JJTCLASSDECLARATION = 20;
  public int JJTCLASSNAME = 21;
  public int JJTEXTENDS = 22;
  public int JJTLINESTATEMENT = 23;
  public int JJTSEMICOLON = 24;
  public int JJTIFSTATEMENT = 25;
  public int JJTIFEXPRESSION = 26;
  public int JJTELSE = 27;
  public int JJTWHILESTATEMENT = 28;
  public int JJTWHILEEXPRESSION = 29;
  public int JJTAND = 30;
  public int JJTLESS = 31;
  public int JJTPLUS = 32;
  public int JJTMINUS = 33;
  public int JJTMULT = 34;
  public int JJTDIV = 35;
  public int JJTINTEGERLITERAL = 36;
  public int JJTTRUE = 37;
  public int JJTFALSE = 38;
  public int JJTTHIS = 39;
  public int JJTNEW = 40;
  public int JJTLEFTPARENTHESES = 41;
  public int JJTRIGHTPARENTHESES = 42;
  public int JJTNEGATION = 43;
  public int JJTARRAY = 44;
  public int JJTLENGTH = 45;
  public int JJTARGUMENTS = 46;
  public int JJTARGUMENT = 47;


  public String[] jjtNodeName = {
    "JavaMM",
    "ImportDeclaration",
    "Static",
    "Identifier",
    "void",
    "Dot",
    "ReturnImport",
    "ImportArgs",
    "Type",
    "MethodDeclaration",
    "MethodHeader",
    "Modifier",
    "MainArgs",
    "MainDeclaration",
    "MethodArguments",
    "VariableDeclaration",
    "ClassType",
    "VariableName",
    "Equal",
    "Return",
    "ClassDeclaration",
    "ClassName",
    "Extends",
    "LineStatement",
    "Semicolon",
    "IfStatement",
    "IfExpression",
    "Else",
    "WhileStatement",
    "WhileExpression",
    "And",
    "Less",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "IntegerLiteral",
    "True",
    "False",
    "This",
    "New",
    "LeftParentheses",
    "RightParentheses",
    "Negation",
    "Array",
    "Length",
    "Arguments",
    "Argument",
  };
}
/* JavaCC - OriginalChecksum=8cb5d4ba22330133e02e6785a132767c (do not edit this line) */
